name: Build CV
on:
  workflow_dispatch:
  push:
    branches:
      - mistress
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Compile Typst Files
      uses: ammar-ahmed22/compile-typst-action@v1
      with:
        source_paths: 'cv_2025.typ cv_2025_en.typ'
        output_paths: 'cv_2025.pdf cv_2025_en.pdf'
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PDF
        path: '**/*.pdf'
    - name: Commit compiled PDFs
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: '[continuous deployment]: Compiled Typst to PDF'
