name: Compile and Commit Typst Files
on:
  push:
    paths:
      - cv_2025.typ
      - cv_2025_en.typ
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Typst 
        run: |
          wget https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz 
          tar xvf typst-x86_64-unknown-linux-musl.tar.xz 
          mv typst-x86_64-unknown-linux-musl/typst . 
      - name: Compile Files
        run: | 
          ./typst c cv_2025.typ
          ./typst c cv_2025_en.typ
      - name: Clean 
        run: |
          rm -rf typst*
      - name: Commit compiled PDFs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[continuous deployment]: Compiled Typst to PDF'
